### ISSUE TITLE
Beta launch checklist (May 22nd)

### ISSUE THREAD

**Issue by garethfuller** [balancer/frontend-v3#471]
TODO
- [x] Pool action blocking if not on v2 pool allowlist (metadata feeds into API) - Token whitelisting might make this redudant, Franz to report
- [ ] Pool action blocking if rate provider not reviewed (metadata feeds into API) - Franz to action
- [x] Receipt pages
- [x] Smooth flow from add to stake
- [ ] Smooth flow from unstake to remove
- [x] Fixed APR sorting
- [x] Incentivised pool filter
- [x] Min TVL filter

Launch day actions:
- [ ] Discord call for testing
- [ ] Reach out to influencers
- [ ] Potentially use coordinape for incentivised testing
- [ ] Share with partners (Cowswap, Aura, Gyro, Quant)
