### ISSUE TITLE
Prod launch checklist (July 1st?)

### ISSUE THREAD

**Issue by garethfuller** [balancer/frontend-v3#472]
- [x] [Beta launch checklist](https://github.com/balancer/frontend-v3/issues/471)
- [x] Pools list redesign
- [x] Pool page redesign
- [ ] Co-branded pool pages
- [ ] Claiming issues
- [ ] Portfolio issues
- [ ] vebal position shown in portfolio
- [ ] Marketing pages
- [ ] COW AMM pool support
