### ISSUE TITLE
V2 UI deprecation checklist

### ISSUE THREAD

**Issue by garethfuller** [balancer/frontend-v3#473]
- [ ] All pool types exitable in v3 UI
- [ ] vebal UI migrated to v3
- [ ] CSP issue recovery exit page left as a standalone app? i.e. everything else in v2 app deleted.
- [ ] No deps left for v1 API so we can delete that.
- [ ] SEO redirects
